-- MySQL Script generated by MySQL Workbench
-- 11/29/17 23:31:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`video` (
  `idvideo` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `director` VARCHAR(45) NULL,
  `creacion` INT NULL,
  `genero` VARCHAR(45) NULL,
  PRIMARY KEY (`idvideo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`series` (
  `idseries` INT NOT NULL,
  `nocapitulos` INT NULL,
  `temporada` INT NULL,
  `video_idvideo` INT NOT NULL,
  PRIMARY KEY (`idseries`),
  INDEX `fk_series_video_idx` (`video_idvideo` ASC),
  CONSTRAINT `fk_series_video`
    FOREIGN KEY (`video_idvideo`)
    REFERENCES `mydb`.`video` (`idvideo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`documentales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`documentales` (
  `iddocumentales` INT NOT NULL,
  `genero` VARCHAR(45) NULL,
  `video_idvideo` INT NOT NULL,
  PRIMARY KEY (`iddocumentales`),
  INDEX `fk_documentales_video1_idx` (`video_idvideo` ASC),
  CONSTRAINT `fk_documentales_video1`
    FOREIGN KEY (`video_idvideo`)
    REFERENCES `mydb`.`video` (`idvideo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`peliculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`peliculas` (
  `idpeliculas` INT NOT NULL,
  `actores` VARCHAR(45) NULL,
  `video_idvideo` INT NOT NULL,
  PRIMARY KEY (`idpeliculas`),
  INDEX `fk_peliculas_video1_idx` (`video_idvideo` ASC),
  CONSTRAINT `fk_peliculas_video1`
    FOREIGN KEY (`video_idvideo`)
    REFERENCES `mydb`.`video` (`idvideo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ususario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ususario` (
  `idususario` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `region` VARCHAR(45) NULL,
  PRIMARY KEY (`idususario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pagos` (
  `idpagos` INT NOT NULL,
  `fecha` VARCHAR(45) NULL,
  `monto` INT NULL,
  `pagos_idpagos` INT NOT NULL,
  `video_idvideo` INT NOT NULL,
  `ususario_idususario` INT NOT NULL,
  PRIMARY KEY (`idpagos`),
  INDEX `fk_pagos_video1_idx` (`video_idvideo` ASC),
  INDEX `fk_pagos_ususario1_idx` (`ususario_idususario` ASC),
  CONSTRAINT `fk_pagos_video1`
    FOREIGN KEY (`video_idvideo`)
    REFERENCES `mydb`.`video` (`idvideo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagos_ususario1`
    FOREIGN KEY (`ususario_idususario`)
    REFERENCES `mydb`.`ususario` (`idususario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sesion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sesion` (
  `idsesion` INT NOT NULL,
  `ubicacion` VARCHAR(45) NULL,
  `video_idvideo` INT NOT NULL,
  `ususario_idususario` INT NOT NULL,
  PRIMARY KEY (`idsesion`),
  INDEX `fk_sesion_video1_idx` (`video_idvideo` ASC),
  INDEX `fk_sesion_ususario1_idx` (`ususario_idususario` ASC),
  CONSTRAINT `fk_sesion_video1`
    FOREIGN KEY (`video_idvideo`)
    REFERENCES `mydb`.`video` (`idvideo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sesion_ususario1`
    FOREIGN KEY (`ususario_idususario`)
    REFERENCES `mydb`.`ususario` (`idususario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carrito` (
  `idcarrito` INT NOT NULL,
  `monto` INT NULL,
  `ususario_idususario` INT NOT NULL,
  PRIMARY KEY (`idcarrito`),
  INDEX `fk_carrito_ususario1_idx` (`ususario_idususario` ASC),
  CONSTRAINT `fk_carrito_ususario1`
    FOREIGN KEY (`ususario_idususario`)
    REFERENCES `mydb`.`ususario` (`idususario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
